import { describe, it, expect } from "vitest";
import { formatHTML } from "../src/formatter/html";
import { formatMarkdown } from "../src/formatter/markdown";
import { Violation } from "../src/rules/types";

const violations: Violation[] = [
  {
    rule: "MV1001",
    severity: "error",
    message: "runAsNonRoot not set to true",
    resource: "Deployment/nginx",
    fix: "Set runAsNonRoot: true\n```yaml\nsecurityContext:\n  runAsNonRoot: true\n```",
  },
  {
    rule: "MV1008",
    severity: "warning",
    message: "no resource limits set",
    resource: "Deployment/nginx",
  },
  {
    rule: "MV6001",
    severity: "info",
    message: "missing recommended labels",
    resource: "Service/frontend",
  },
];

describe("formatHTML", () => {
  it("returns a valid HTML document", () => {
    const html = formatHTML(violations);
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("<html");
    expect(html).toContain("</html>");
  });

  it("includes violation details", () => {
    const html = formatHTML(violations);
    expect(html).toContain("MV1001");
    expect(html).toContain("Deployment/nginx");
    expect(html).toContain("runAsNonRoot not set to true");
  });

  it("includes severity badges", () => {
    const html = formatHTML(violations);
    expect(html).toContain("error");
    expect(html).toContain("warning");
    expect(html).toContain("info");
  });

  it("shows fix suggestion when present", () => {
    const html = formatHTML(violations);
    expect(html).toContain("修正方法");
    expect(html).toContain("runAsNonRoot");
  });

  it("shows no issues message for empty violations", () => {
    const html = formatHTML([]);
    expect(html).toContain("No issues found");
  });

  it("escapes HTML special characters", () => {
    const xssViolations: Violation[] = [{
      rule: "MV1001",
      severity: "error",
      message: "<script>alert('xss')</script>",
      resource: "Deployment/app",
    }];
    const html = formatHTML(xssViolations);
    expect(html).not.toContain("<script>");
    expect(html).toContain("&lt;script&gt;");
  });
});

describe("formatMarkdown", () => {
  it("includes markdown header", () => {
    const md = formatMarkdown(violations);
    expect(md).toContain("## ManifestVet Scan Results");
  });

  it("includes violation table", () => {
    const md = formatMarkdown(violations);
    expect(md).toContain("| Rule | Severity | Message |");
    expect(md).toContain("`MV1001`");
    expect(md).toContain("Deployment/nginx");
  });

  it("includes fix suggestions in collapsible section", () => {
    const md = formatMarkdown(violations);
    expect(md).toContain("<details>");
    expect(md).toContain("Fix suggestions");
    expect(md).toContain("runAsNonRoot");
  });

  it("shows success message for empty violations", () => {
    const md = formatMarkdown([]);
    expect(md).toContain("No issues found");
    expect(md).not.toContain("<details>");
  });

  it("groups violations by resource", () => {
    const md = formatMarkdown(violations);
    expect(md).toContain("#### `Deployment/nginx`");
    expect(md).toContain("#### `Service/frontend`");
  });

  it("includes footer", () => {
    const md = formatMarkdown(violations);
    expect(md).toContain("Generated by");
    expect(md).toContain("ManifestVet");
  });

  it("includes severity emojis", () => {
    const md = formatMarkdown(violations);
    expect(md).toContain("🔴");
    expect(md).toContain("🟡");
    expect(md).toContain("🔵");
  });
});
