import { describe, it, expect } from "vitest";
import { formatHTML } from "../src/formatter/html";
import { formatMarkdown } from "../src/formatter/markdown";
import { Violation } from "../src/rules/types";

const violations: Violation[] = [
  {
    rule: "MV1001",
    severity: "high",
    message: "runAsNonRoot not set to true",
    resource: "Deployment/nginx",
    fix: "Set runAsNonRoot: true\n```yaml\nsecurityContext:\n  runAsNonRoot: true\n```",
  },
  {
    rule: "MV1008",
    severity: "medium",
    message: "no resource limits set",
    resource: "Deployment/nginx",
  },
  {
    rule: "MV6001",
    severity: "low",
    message: "missing recommended labels",
    resource: "Service/frontend",
  },
];

describe("formatHTML", () => {
  it("returns a valid HTML document", () => {
    const html = formatHTML(violations);
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("<html");
    expect(html).toContain("</html>");
  });

  it("includes violation details", () => {
    const html = formatHTML(violations);
    expect(html).toContain("MV1001");
    expect(html).toContain("Deployment/nginx");
    expect(html).toContain("runAsNonRoot not set to true");
  });

  it("includes severity badges", () => {
    const html = formatHTML(violations);
    expect(html).toContain("high");
    expect(html).toContain("medium");
    expect(html).toContain("low");
  });

  it("shows fix suggestion when present", () => {
    const html = formatHTML(violations);
    expect(html).toContain("修正方法");
    expect(html).toContain("runAsNonRoot");
  });

  it("shows no issues message for empty violations", () => {
    const html = formatHTML([]);
    expect(html).toContain("No issues found");
  });

  it("returns a string for empty violations", () => {
    const html = formatHTML([]);
    expect(typeof html).toBe("string");
    expect(html.length).toBeGreaterThan(0);
    expect(html).toContain("<!DOCTYPE html>");
  });

  it("correctly counts by severity", () => {
    const html = formatHTML(violations);
    // violations has 1 high, 1 medium, 1 low
    const highCount   = violations.filter((v) => v.severity === "high").length;
    const mediumCount = violations.filter((v) => v.severity === "medium").length;
    const lowCount    = violations.filter((v) => v.severity === "low").length;
    expect(highCount).toBe(1);
    expect(mediumCount).toBe(1);
    expect(lowCount).toBe(1);
    // Verify the counts are reflected in the rendered HTML
    expect(html).toContain("Critical");
    expect(html).toContain("High");
    expect(html).toContain("Medium");
    expect(html).toContain("Low");
    expect(html).toContain("Info");
  });

  it("reflects zero counts for empty violations", () => {
    const html = formatHTML([]);
    expect(html).toContain("0");
  });

  it("handles violations with only critical/high", () => {
    const errorOnly: Violation[] = [
      { rule: "MV1001", severity: "high", message: "error msg", resource: "Pod/foo" },
      { rule: "MV1003", severity: "critical", message: "error msg 2", resource: "Pod/bar" },
    ];
    const html = formatHTML(errorOnly);
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("MV1001");
    expect(html).toContain("MV1003");
  });

  it("uses custom title when provided", () => {
    const html = formatHTML(violations, "Custom Report Title");
    expect(html).toContain("Custom Report Title");
  });

  it("escapes HTML special characters", () => {
    const xssViolations: Violation[] = [{
      rule: "MV1001",
      severity: "high",
      message: "<script>alert('xss')</script>",
      resource: "Deployment/app",
    }];
    const html = formatHTML(xssViolations);
    expect(html).not.toContain("<script>");
    expect(html).toContain("&lt;script&gt;");
  });
});

describe("formatMarkdown", () => {
  it("includes markdown header", () => {
    const md = formatMarkdown(violations);
    expect(md).toContain("## ManifestVet Scan Results");
  });

  it("includes violation table", () => {
    const md = formatMarkdown(violations);
    expect(md).toContain("| Rule | Severity | Message |");
    expect(md).toContain("`MV1001`");
    expect(md).toContain("Deployment/nginx");
  });

  it("includes fix suggestions in collapsible section", () => {
    const md = formatMarkdown(violations);
    expect(md).toContain("<details>");
    expect(md).toContain("Fix suggestions");
    expect(md).toContain("runAsNonRoot");
  });

  it("shows success message for empty violations", () => {
    const md = formatMarkdown([]);
    expect(md).toContain("No issues found");
    expect(md).not.toContain("<details>");
  });

  it("groups violations by resource", () => {
    const md = formatMarkdown(violations);
    expect(md).toContain("#### `Deployment/nginx`");
    expect(md).toContain("#### `Service/frontend`");
  });

  it("includes footer", () => {
    const md = formatMarkdown(violations);
    expect(md).toContain("Generated by");
    expect(md).toContain("ManifestVet");
  });

  it("includes severity emojis", () => {
    const md = formatMarkdown(violations);
    expect(md).toContain("🟠"); // high
    expect(md).toContain("🟡"); // medium
    expect(md).toContain("🟢"); // low
  });
});
