import { Violation, Severity } from "../rules/types";

function severityEmoji(severity: Severity): string {
  switch (severity) {
    case "error":   return "🔴";
    case "warning": return "🟡";
    case "info":    return "🔵";
  }
}

function groupByResource(violations: Violation[]): Map<string, Violation[]> {
  const map = new Map<string, Violation[]>();
  for (const v of violations) {
    const list = map.get(v.resource) ?? [];
    list.push(v);
    map.set(v.resource, list);
  }
  return map;
}

export function formatMarkdown(violations: Violation[]): string {
  const errors   = violations.filter((v) => v.severity === "error").length;
  const warnings = violations.filter((v) => v.severity === "warning").length;
  const infos    = violations.filter((v) => v.severity === "info").length;

  const lines: string[] = [];

  // Header
  lines.push("## ManifestVet Scan Results");
  lines.push("");

  if (violations.length === 0) {
    lines.push("✅ **No issues found.** All manifests passed security checks.");
    return lines.join("\n");
  }

  // Summary badges (GitHub-style)
  const badge = (label: string, count: number, color: string) =>
    count > 0 ? `![${label}: ${count}](https://img.shields.io/badge/${label}-${count}-${color})` : "";

  const badges = [
    badge("errors", errors, "critical"),
    badge("warnings", warnings, "important"),
    badge("info", infos, "informational"),
  ].filter(Boolean);

  if (badges.length) {
    lines.push(badges.join(" "));
    lines.push("");
  }

  // Summary table
  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  if (errors   > 0) lines.push(`| 🔴 Error   | ${errors}   |`);
  if (warnings > 0) lines.push(`| 🟡 Warning | ${warnings} |`);
  if (infos    > 0) lines.push(`| 🔵 Info    | ${infos}    |`);
  lines.push("");

  // Violations by resource
  lines.push("### Violations");
  lines.push("");

  const grouped = groupByResource(violations);

  for (const [resource, vs] of grouped.entries()) {
    lines.push(`#### \`${resource}\``);
    lines.push("");
    lines.push("| Rule | Severity | Message |");
    lines.push("|------|----------|---------|");
    for (const v of vs) {
      const emoji = severityEmoji(v.severity);
      lines.push(
        `| \`${v.rule}\` | ${emoji} ${v.severity} | ${v.message.replace(/\|/g, "\\|")} |`
      );
    }
    lines.push("");

    // Fix suggestions (collapsible)
    const withFix = vs.filter((v) => v.fix);
    if (withFix.length > 0) {
      lines.push("<details>");
      lines.push("<summary>💡 Fix suggestions</summary>");
      lines.push("");
      for (const v of withFix) {
        lines.push(`**\`${v.rule}\`**`);
        lines.push("");
        lines.push(v.fix!);
        lines.push("");
      }
      lines.push("</details>");
      lines.push("");
    }
  }

  // Footer
  lines.push("---");
  lines.push("*Generated by [ManifestVet](https://github.com/manifestvet/manifestvet)*");

  return lines.join("\n");
}
