import { Violation, Severity } from "../rules/types";

function severityEmoji(severity: Severity): string {
  switch (severity) {
    case "critical": return "🔴";
    case "high":     return "🟠";
    case "medium":   return "🟡";
    case "low":      return "🟢";
    case "info":     return "🔵";
  }
}

function groupByResource(violations: Violation[]): Map<string, Violation[]> {
  const map = new Map<string, Violation[]>();
  for (const v of violations) {
    const list = map.get(v.resource) ?? [];
    list.push(v);
    map.set(v.resource, list);
  }
  return map;
}

export function formatMarkdown(violations: Violation[]): string {
  const counts: Partial<Record<Severity, number>> = {};
  for (const v of violations) {
    counts[v.severity] = (counts[v.severity] ?? 0) + 1;
  }
  const critical = counts.critical ?? 0;
  const high     = counts.high     ?? 0;
  const medium   = counts.medium   ?? 0;
  const low      = counts.low      ?? 0;
  const info     = counts.info     ?? 0;

  const lines: string[] = [];

  // Header
  lines.push("## ManifestVet Scan Results");
  lines.push("");

  if (violations.length === 0) {
    lines.push("✅ **No issues found.** All manifests passed security checks.");
    return lines.join("\n");
  }

  // Summary badges (GitHub-style)
  const badge = (label: string, count: number, color: string) =>
    count > 0 ? `![${label}: ${count}](https://img.shields.io/badge/${label}-${count}-${color})` : "";

  const badges = [
    badge("critical", critical, "critical"),
    badge("high",     high,     "red"),
    badge("medium",   medium,   "important"),
    badge("low",      low,      "yellow"),
    badge("info",     info,     "informational"),
  ].filter(Boolean);

  if (badges.length) {
    lines.push(badges.join(" "));
    lines.push("");
  }

  // Summary table
  lines.push("| Severity | Count |");
  lines.push("|----------|-------|");
  if (critical > 0) lines.push(`| 🔴 Critical | ${critical} |`);
  if (high     > 0) lines.push(`| 🟠 High     | ${high}     |`);
  if (medium   > 0) lines.push(`| 🟡 Medium   | ${medium}   |`);
  if (low      > 0) lines.push(`| 🟢 Low      | ${low}      |`);
  if (info     > 0) lines.push(`| 🔵 Info     | ${info}     |`);
  lines.push("");

  // Violations by resource
  lines.push("### Violations");
  lines.push("");

  const grouped = groupByResource(violations);

  for (const [resource, vs] of grouped.entries()) {
    lines.push(`#### \`${resource}\``);
    lines.push("");
    lines.push("| Rule | Severity | Message |");
    lines.push("|------|----------|---------|");
    for (const v of vs) {
      const emoji = severityEmoji(v.severity);
      lines.push(
        `| \`${v.rule}\` | ${emoji} ${v.severity} | ${v.message.replace(/\|/g, "\\|")} |`
      );
    }
    lines.push("");

    // Fix suggestions (collapsible)
    const withFix = vs.filter((v) => v.fix);
    if (withFix.length > 0) {
      lines.push("<details>");
      lines.push("<summary>💡 Fix suggestions</summary>");
      lines.push("");
      for (const v of withFix) {
        lines.push(`**\`${v.rule}\`**`);
        lines.push("");
        lines.push(v.fix!);
        lines.push("");
      }
      lines.push("</details>");
      lines.push("");
    }
  }

  // Footer
  lines.push("---");
  lines.push("*Generated by [ManifestVet](https://github.com/manifestvet/manifestvet)*");

  return lines.join("\n");
}
